source:
    path: "{{ user.home }}/www"
    github:
        - { org: bolt, repo: bolt }
        - { org: chjj, repo: blessed }
        - { org: dantleech, repo: system }
        - { org: dantleech, repo: dtlweb }
        - { org: dantleech, repo: Trainer }
        - { org: dantleech, repo: skeletor }
        - { org: dantleech, repo: sf-http-cache-tagging }
        - { org: phpbench, repo: phpbench }
        - { org: phpbench, repo: cellular }
        - { org: phpbench, repo: tabular }
        - { org: CouscousPHP, repo: Couscous }
        - { org: CouscousPHP, repo: Template-Dark }
        - { org: doctrine, repo: DoctrinePHPCRBundle }
        - { org: doctrine, repo: doctrine2 }
        - { org: doctrine, repo: phpcr-odm }
        - { org: KnpLabs, repo: php-github-api }
        - { org: FriendsOfSymfony, repo: FosHttpCache }
        - { org: FriendsOfSymfony, repo: FosHttpCacheBundle }
        - { org: hoaproject, repo: Math }
        - { org: jackalope, repo: jackalope }
        - { org: jackalope, repo: jackalope-doctrine-dbal }
        - { org: jackalope, repo: jackalope-jackrabbit }
        - { org: jackalope, repo: jackalope-fs }
        - { org: letsencrypt, repo: letsencrypt }
        - { org: massiveart, repo: MassiveBuildBundle }
        - { org: massiveart, repo: MassiveSearchBundle }
        - { org: massiveart, repo: husky }
        - { org: neovim, repo: neovim }
        - { org: puli, repo: puli }
        - { org: puli, repo: repository }
        - { org: phpcr, repo: phpcr }
        - { org: phpcr, repo: phpcr-benchmarks }
        - { org: phpcr, repo: phpcr-migrations }
        - { org: phpcr, repo: phpcr-shell }
        - { org: phpcr, repo: phpcr-utils }
        - { org: phpcr, repo: phpcr-api-tests }
        - { org: phpspec, repo: prophecy }
        - { org: schmittjoh, repo: JMSSerializerBundle }
        - { org: schmittjoh, repo: serializer }
        - { org: sonata-project, repo: SonataDoctrinePhpcrAdminBundle }
        - { org: stage1, repo: docker-php }
        - { org: sulu-io, repo: docs }
        - { org: sulu-io, repo: sulu }
        - { org: sulu-io, repo: sulu-docs }
        - { org: sulu-io, repo: sulu-standard }
        - { org: sulu-io, repo: sulu-document-manager }
        - { org: sylius, repo: sylius }
        - { org: symfony, repo: symfony }
        - { org: symfony, repo: symfony-docs }
        - { org: symfony-cmf, repo: Resource }
        - { org: symfony-cmf, repo: ResourceBundle }
        - { org: symfony-cmf, repo: ResourceRestBundle }
        - { org: symfony-cmf, repo: Routing }
        - { org: symfony-cmf, repo: RoutingBundle }
        - { org: symfony-cmf, repo: RoutingAuto }
        - { org: symfony-cmf, repo: RoutingAutoBundle }
        - { org: symfony-cmf, repo: MenuBundle }
        - { org: symfony-cmf, repo: Testing }
        - { org: symfony-cmf, repo: slugifier-api }
        - { org: symfony-cmf, repo: symfony-cmf-website }
        - { org: symfony-cmf, repo: symfony-cmf-docs }
        - { org: symfony-cmf, repo: cmf-sandbox }
        - { org: webmozart, repo: console }
        - { org: zendframework, repo: zend-servicemanager }

hosts:
    - 
      host: "sulu.lo"
      path: "sulu-io/sulu-standard/web"
    - 
      host: "suludm.lo"
      path: "sulu-io/sulu-object-mapper-edition/web"
    - 
      host: "cmf-website.lo"
      path: "symfony-cmf/symfony-cmf-website/web"
    - 
      host: "stanton.lo"
      path: "sulu-io/st-anton-am-arlberg/www.stantonamarlberg.com"
    - 
      host: "stantondm.lo"
      path: "sulu-io/st-anton-am-arlberg-dm/www.stantonamarlberg.com"

tmux_profile_dir: "{{ user.home }}/.tmuxinator"
