- name: Install packages
  sudo: True
  apt: pkg={{ item }} state=present
  with_items:
      - "ruby"

- name: Install tmuxinator
  sudo: True
  gem: name=tmuxinator state=present user_install=no

- name: Create directory
  file: path="{{ user.home }}/.tmuxinator" state=directory

- name: Install profiles
  copy: src=mux/ dest={{ user.home }}/.tmuxinator
