- name: Install packages
  sudo: True
  apt: pkg={{ item }} state=present
  with_items:
      - "vim-gtk"

- name: vimrc
  template: src=vimrc dest="{{ user.home }}/.vimrc"

- name: Install Vundle
  git: repo=git@github.com:gmarik/Vundle.vim.git dest={{ user.home }}/.vim/bundle/Vundle.vim

- name: Install PDV templates
  copy: src=vim_pdv_templates_snip dest={{ vim.pdv_template_dir }}

#- name: Update bundles
#  command: vim -c "BundleInstall" -c "qa"
