- include: awesome.yml tags=awesome
- include: privoxy.yml tags=privoxy
- include: vimb.yml tags=vimb
- include: weechat.yml tags=weechat
- include: mpd.yml tags=mpd
- include: terminal.yml tags=terminal
- include: screensaver.yml tags=screensaver
- include: syncthing.yml tags=syncthing
- include: screenshot.yml tags=screenshot
